a = (int)(input("enter first number : "))
b = (int)(input("enter second number : "))
print(f"sum of {a} and {b} is {a+b}")
print(f"product of {a} and {b} is {a*b}")
print(f"difference between {a} and {b} is {a-b}")
print(f"division of {a} and {b} is {a/b}")
print(f"remainder of {a} and {b} is {a%b}")